apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch1-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ch1
  template:
    metadata:
      labels:
        app: ch1
    spec:
      hostname: ch1-host
      containers:
        - image: keks51-centos7
          imagePullPolicy: Never
          securityContext:
            privileged: true
          name: ch1
          ports:
            - containerPort: 8000
            - containerPort: 22
              name: ssh-port
---
apiVersion: v1
kind: Service
metadata:
  name: ch1
spec:
  selector:
    app: ch1
  ports:
    - port: 8020
      targetPort: 8020
      name: fs-default
      protocol: TCP
    - name: ssh-port
      port: 22
      protocol: TCP
      targetPort: ssh-port